const nome = prompt("Digite seu nome completo:")
const nascimento = prompt("Digite sua data de nascimento:")
const endereco = prompt("Digite seu endereço:")
const cpf = prompt("Digite seu CPF:")
const escolaridade = prompt("Digite sua escolaridade:")
const cnh = prompt("Possui CNH?")
const quantFilhos = Number(prompt("Quantos filhos possui?"))
const cargo = prompt("Digite seu cargo atual:")
const salario = Number(prompt("Qual seu salário?"))
const comissao = Number(prompt("Recebe comissão? Se sim, informe a porcentagem (sem o %), caso não, responda com zero"))
const anoAdmissao = Number(prompt("Informe ano de admissão:"))

console.log(typeof nome)
console.log(typeof nascimento)
console.log(typeof endereco)
console.log(typeof cpf)
console.log(typeof escolaridade)
console.log(typeof cnh)
console.log(typeof quantFilhos)
console.log(typeof cargo)
console.log(typeof salario)
console.log(typeof comissao)
console.log(typeof anoAdmissao)

console.log("Nome:", nome)
console.log("Data de nascimento:", nascimento)
console.log("Endereço:", endereco)
console.log("CPF:", cpf)
console.log("Escolaridade:", escolaridade)
console.log("Possui CNH?", cnh)
console.log("Quantos filhos tem?", quantFilhos)
console.log("Cargo atual:", cargo)
console.log("Salário:", salario)
console.log("Comissão:", comissao, "%")
console.log("Ano de admissão:", anoAdmissao)